[package]
name = "branch-and-bound"
version = "0.1.0"
authors = ["Daniela Brozzoni <brozzoni@live.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3"

[dependencies.bitcoin]
version = "0.21"
